name: mcsakura
main: com.github.ujihisa.Mcsakura.JRubyPlugin
version: 1.0.0
website: http://ujihisa.blogspot.com
author: Tatsuhiro Ujihisa
description: ask @ujm
commands:
  mckokoro:
    description: debugging
    usage: /mckokoro [anything]
  inv:
    description: Inventory Everywhere.
    usage: /inv
  lingr:
    description: Post a message to lingr.
    usage: /lingr [anything]
#depend: [ControllableMobsAPI]
